- hosts: localhost
  connection: local
  become: True
  tasks:
    - include_vars: fufu.yml

    - name: user setup in mysql
      mysql_user:
       user: root
       password: '{{ mysql_pass }}'
       host: localhost
       priv: '*.*:ALL,GRANT'
       login_unix_socket: /var/run/mysqld/mysqld.sock