# reference
# https://gist.github.com/komuw/b3b5d24977d4df7bd549

- hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Install curl
      apt: name=curl
    
    - name: Install nvm
      shell: >
        curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | sh
        creates=~/.nvm/nvm.sh
    
    - name: Install node 18.17.0 and set version
      shell: >
        /bin/bash -c "source ~/.nvm/nvm.sh && nvm install 18.17.0 && nvm alias default 18.17.0"
        creates=~/.nvm/alias